/**
 * Maintenance Data Service
 * 
 * This service loads maintenance data from the CSV file generated by the
 * FlightDocs scraper script located at /src/imports/flightdocs-scraper.ts
 * 
 * SETUP INSTRUCTIONS FOR AUTOMATED SCRAPER:
 * 
 * 1. Install dependencies (in a separate Node.js environment):
 *    npm install playwright xlsx
 *    npx playwright install chromium
 * 
 * 2. Set environment variables:
 *    Windows PowerShell:
 *      setx FLIGHTDOCS_USERNAME "your.email@example.com"
 *      setx FLIGHTDOCS_PASSWORD "your_password"
 *    
 *    Linux/Mac:
 *      export FLIGHTDOCS_USERNAME="your.email@example.com"
 *      export FLIGHTDOCS_PASSWORD="your_password"
 * 
 * 3. Update the OUTPUT_PATH in the scraper to point to /public/data/due-list.csv
 * 
 * 4. Schedule daily execution:
 * 
 *    Windows Task Scheduler:
 *      - Open Task Scheduler
 *      - Create Basic Task
 *      - Trigger: Daily at 2:00 AM
 *      - Action: Start a program
 *      - Program: node
 *      - Arguments: "C:\path\to\project\src\imports\flightdocs-scraper.ts"
 * 
 *    Linux/Mac Cron:
 *      crontab -e
 *      Add line: 0 2 * * * cd /path/to/project && node src/imports/flightdocs-scraper.ts
 * 
 *    GitHub Actions (recommended for cloud deployment):
 *      Create .github/workflows/scrape-flightdocs.yml with scheduled workflow
 */

import { Aircraft, InspectionHours, Component } from '../data/mockData';

export interface FlightDocsRow {
  aircraft: string;
  registration: string;
  item: string;
  serialNumber: string;
  dueAt: number;
  currentTime: number;
  remaining: number;
  status: string;
}

/**
 * Parse CSV data from FlightDocs export
 */
export function parseFlightDocsCsv(csvText: string): FlightDocsRow[] {
  const lines = csvText.trim().split('\n');
  if (lines.length === 0) return [];

  const headers = lines[0].split(',').map(h => h.trim().toLowerCase());
  const data: FlightDocsRow[] = [];

  for (let i = 1; i < lines.length; i++) {
    const values = lines[i].split(',');
    if (values.length < headers.length) continue;

    const row: any = {};
    headers.forEach((header, index) => {
      row[header] = values[index]?.trim() || '';
    });

    // Map to our structure (adjust field names based on actual CSV headers)
    data.push({
      aircraft: row['aircraft'] || row['tail number'] || '',
      registration: row['registration'] || row['n-number'] || '',
      item: row['item'] || row['description'] || '',
      serialNumber: row['serial number'] || row['s/n'] || '',
      dueAt: parseFloat(row['due at'] || row['due'] || '0'),
      currentTime: parseFloat(row['current time'] || row['hours'] || '0'),
      remaining: parseFloat(row['remaining'] || '0'),
      status: row['status'] || '',
    });
  }

  return data;
}

/**
 * Load maintenance data from the CSV file
 * In production, this would fetch from the /public/data/ directory
 */
export async function loadMaintenanceData(): Promise<{
  aircraft: Aircraft[];
  inspections: InspectionHours[];
  components: { aircraftId: string; registration: string; components: Component[] }[];
}> {
  try {
    // Try to load the CSV file from public directory
    const response = await fetch('/data/due-list.csv');
    
    if (!response.ok) {
      console.warn('CSV file not found, using mock data. Run the FlightDocs scraper to populate real data.');
      throw new Error('CSV not found');
    }

    const csvText = await response.text();
    const rows = parseFlightDocsCsv(csvText);

    // Transform CSV rows into our application data structure
    return transformFlightDocsData(rows);
  } catch (error) {
    console.error('Error loading maintenance data:', error);
    // Return empty data structure - the app will use mock data instead
    return {
      aircraft: [],
      inspections: [],
      components: [],
    };
  }
}

/**
 * Transform FlightDocs CSV data into application format
 */
function transformFlightDocsData(rows: FlightDocsRow[]): {
  aircraft: Aircraft[];
  inspections: InspectionHours[];
  components: { aircraftId: string; registration: string; components: Component[] }[];
} {
  // Group by aircraft
  const byAircraft = new Map<string, FlightDocsRow[]>();
  
  rows.forEach(row => {
    const reg = row.registration || row.aircraft;
    if (!reg) return;
    
    if (!byAircraft.has(reg)) {
      byAircraft.set(reg, []);
    }
    byAircraft.get(reg)!.push(row);
  });

  const aircraft: Aircraft[] = [];
  const inspections: InspectionHours[] = [];
  const components: { aircraftId: string; registration: string; components: Component[] }[] = [];

  let aircraftIndex = 0;

  byAircraft.forEach((items, registration) => {
    const aircraftId = `AC${String(++aircraftIndex).padStart(3, '0')}`;
    
    // Calculate current time (use the max current time from items)
    const currentTime = Math.max(...items.map(i => i.currentTime), 0);
    
    // Find hours until next 200-hour inspection
    const hoursUntil200Hr = 200 - (currentTime % 200);
    
    // Calculate average utilization (you may need historical data for this)
    const averageUtilization = 4.5; // Default, update with real data

    aircraft.push({
      id: aircraftId,
      registration,
      totalTime: currentTime,
      hoursUntil200Hr,
      averageUtilization,
      status: 'on-ground',
    });

    // Separate inspection items and component items
    const inspectionItems: { [key: string]: number } = {};
    const componentItems: Component[] = [];

    items.forEach(item => {
      const isInspection = 
        item.item.toLowerCase().includes('inspection') ||
        item.item.toLowerCase().includes('check') ||
        item.item.toLowerCase().includes('annual') ||
        item.item.toLowerCase().includes('100 hour');

      if (isInspection) {
        inspectionItems[item.item] = item.remaining;
      } else {
        componentItems.push({
          id: `${aircraftId}-${componentItems.length + 1}`,
          name: item.item,
          serialNumber: item.serialNumber,
          hoursRemaining: item.remaining,
        });
      }
    });

    if (Object.keys(inspectionItems).length > 0) {
      inspections.push({
        aircraftId,
        registration,
        inspections: inspectionItems,
      });
    }

    if (componentItems.length > 0) {
      components.push({
        aircraftId,
        registration,
        components: componentItems,
      });
    }
  });

  return { aircraft, inspections, components };
}

/**
 * Setup guide for automated daily scraping
 */
export const SCRAPER_SETUP_GUIDE = `
# FlightDocs Scraper - Daily Automation Setup

## Option 1: Windows Task Scheduler

1. Open Task Scheduler (taskschd.msc)
2. Click "Create Basic Task"
3. Name: "FlightDocs Data Sync"
4. Trigger: Daily at 2:00 AM
5. Action: Start a program
   - Program: C:\\Program Files\\nodejs\\node.exe
   - Arguments: "C:\\path\\to\\your\\project\\src\\imports\\flightdocs-scraper.ts"
   - Start in: C:\\path\\to\\your\\project
6. Set credentials environment variables in System Properties

## Option 2: Linux/Mac Cron Job

\`\`\`bash
# Edit crontab
crontab -e

# Add this line (runs daily at 2:00 AM)
0 2 * * * cd /path/to/project && /usr/bin/node src/imports/flightdocs-scraper.ts >> /var/log/flightdocs-scraper.log 2>&1
\`\`\`

## Option 3: GitHub Actions (Recommended for Cloud)

Create \`.github/workflows/scrape-flightdocs.yml\`:

\`\`\`yaml
name: FlightDocs Daily Sync
on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install playwright xlsx
      - run: npx playwright install chromium
      - run: node src/imports/flightdocs-scraper.ts
        env:
          FLIGHTDOCS_USERNAME: \${{ secrets.FLIGHTDOCS_USERNAME }}
          FLIGHTDOCS_PASSWORD: \${{ secrets.FLIGHTDOCS_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: maintenance-data
          path: public/data/due-list.csv
\`\`\`

## Environment Variables

Set these in your system:
- FLIGHTDOCS_USERNAME
- FLIGHTDOCS_PASSWORD
- FLIGHTDOCS_OUTPUT_PATH (optional, defaults to data/due-list.csv)
`;
